package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "core",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    copts = ["-std=c++14"],
)